[package]
description = "Parity Wallet UI server"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "parity-ui-server"
version = "1.7.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore-devtools = { path = "../devtools" }
ethcore-util = { path = "../util" }
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.7" }
jsonrpc-server-utils = { git = "https://github.com/paritytech/jsonrpc.git", branch = "parity-1.7" }
log = "0.3"
parity-rpc = { path = "../rpc" }
rand = "0.3.14"
ws = { git = "https://github.com/paritytech/ws-rs.git", branch = "parity-1.7" }

parity-dapps-glue = { version = "1.7", optional = true }
parity-ui = { path = "../dapps/ui", version = "1.4", optional = true }

clippy = { version = "0.0.103", optional = true}

[features]
dev = ["clippy"]
ui = ["parity-dapps-glue", "parity-ui", "parity-ui/no-precompiled-js"]
ui-precompiled = ["parity-dapps-glue", "parity-ui", "parity-ui/use-precompiled-js"]
